sudo: false

language: php

branches:
  except:
    - /^release-.*$/
    - /^ghgfk-.*$/

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.local
    - zf-mkdoc-theme

env:
  global:
    - SITE_URL: https://zendframework.github.io/zend-permissions-rbac
    - GH_USER_NAME: "Matthew Weier O'Phinney"
    - GH_USER_EMAIL: matthew@weierophinney.net
    - GH_REF: github.com/zendframework/zend-permissions-rbac.git
    - secure: "ELn6js6W0wG3/HlaNJ4ibkLPODT2brDZve6mouEiKnuEvS7dPLQvZYPBr55wWzRG8jGFbTvNXbyMspoufsBuZu5MeSRxkQG0g+Ka/7EXdAJaC/rNJREjMYoFPBS7jzPiEj6M8zi28fEA4rEXQBPkV2XSdXD1dyYFXNXBwcOD+5LEyvFA5A+CNFjfhlf/SDMssJfpmuY+PyyP9r0rIoWwPDrRCQYA3T4vFN6/T6VtrrvSoV32F3Dr7Hjioe57HuTum5UMkVpG8cllx1gQSwqDOE3T1CPejtrgfA6V4UMH1TmNt0GsOCPs+Y0Bjjq30WW5QkFCfk3R27QsJOLKfOr4gsT/oup90x858qrzgmBJio8lOmh4DpaYk3pX96FcP4uS1klyW6m1QkBD+1LkS96BW/pL6gqSu9Xa8nSeC3NRDIzrJf7Yd4YR88xdg0g0UUJ/Z34rdM4kzEeYFuls6zmgnfrmJzOnFU7yWw9CzInMikrx5jQloJUogARr4QsI0MKggw1KNs+ECqAcQbL/wb/EuVUIIB4u0joTn3Ox71x0TZg+MdRIPSWNwuGmJfMZLZ2nIU9To7qHFs1tMgJ/+JRuWrx+UFAelMBoNf0qRqI0XbpTH2R+FM6EiX9aOqPPFt3aYMdfyFzncIGEsoXv5ySECgvoEU41Sszwa23ekgjjxcs="

matrix:
  include:
    - php: 5.5
      env:
        - EXECUTE_CS_CHECK=true
    - php: 5.6
      env:
        - EXECUTE_TEST_COVERALLS=true
        - DEPLOY_DOCS="$(if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then echo -n 'true' ; else echo -n 'false' ; fi)"
        - PATH="$HOME/.local/bin:$PATH"
    - php: 7
    - php: hhvm 
  allow_failures:
    - php: 7
    - php: hhvm

notifications:
  irc: "irc.freenode.org#zftalk.dev"
  email: false

before_install:
  - if [[ $EXECUTE_TEST_COVERALLS != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi
  - composer self-update
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then composer require --dev --no-update satooshi/php-coveralls ; fi

install:
  - travis_retry composer install --no-interaction --ignore-platform-reqs

script:
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then ./vendor/bin/phpunit --coverage-clover clover.xml ; fi
  - if [[ $EXECUTE_TEST_COVERALLS != 'true' ]]; then ./vendor/bin/phpunit ; fi
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then ./vendor/bin/php-cs-fixer fix -v --diff --dry-run ; fi
  - if [[ $DEPLOY_DOCS == "true" && "$TRAVIS_TEST_RESULT" == "0" ]]; then wget -O theme-installer.sh "https://raw.githubusercontent.com/zendframework/zf-mkdoc-theme/master/theme-installer.sh" ; chmod 755 theme-installer.sh ; ./theme-installer.sh ; fi

after_success:
  - if [[ $DEPLOY_DOCS == "true" ]]; then echo "Preparing to build and deploy documentation" ; ./zf-mkdoc-theme/deploy.sh ; echo "Completed deploying documentation" ; fi

after_script:
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then ./vendor/bin/coveralls ; fi
